### ISSUE TITLE
some feedbacks

### ISSUE THREAD

**Issue by aldy505** [elianiva/halu#1]
https://github.com/elianiva/halu/blob/114ef3cb00245c4a8bc25f5bcd0d9f1809006061/main.go#L121

this error should be handled

https://github.com/elianiva/halu/blob/114ef3cb00245c4a8bc25f5bcd0d9f1809006061/main.go#L103

error value should be returned

https://github.com/elianiva/halu/blob/114ef3cb00245c4a8bc25f5bcd0d9f1809006061/main.go#L135

`here` should be `her`

https://github.com/elianiva/halu/blob/114ef3cb00245c4a8bc25f5bcd0d9f1809006061/main.go#L86

`b.Reply` has an error signature, that should also be handled

https://github.com/elianiva/halu/blob/114ef3cb00245c4a8bc25f5bcd0d9f1809006061/main.go#L115

this could be simplified to `resp, err := (&http.Client{}).Do(...)`, or even better put a timeout: `(&http.Client{Timeout: time.Second*30}).Do(...)`

**Comment by elianiva** [comment]
> here should be her

hadeuh kebiasaan typo kelebihan `e` di belakang


btw, thanks
